[package]
name = "icons"
version = "0.1.0"
authors = ["xa1303 <xaveang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusttype = "0.9.2"
image = "0.23.14"
imageproc = "0.22.0"
rand = "0.8.3"